### ISSUE TITLE
Incorrect time

### ISSUE THREAD

**Issue by marekkalnik** [bamlab/google-calendar-counter#3]
Seen with @Spoutnik97 - if window is downsized, the height of the line changes and the time count is incorrect.

**Comment by rachel49207** [comment]
My window is not downsized and my times still are not totalling correctly. An event inputting from 8am-4pm is only totalling as 6 hours 40 minutes. Any ideas for how I can adjust this? Each hour of time is only totalling as 50 minutes?

**Comment by marekkalnik** [comment]
Hi @rachel49207 in the mentionned case, the downsizing was caused by MacOS Dock bar on "open permanently" setting. Would this be your case ?

**Comment by rachel49207** [comment]
I got rid of the permanent bar on my Mac, but Time Spent still isn't calculating correctly on my Mac or my PC.

**Comment by rachel49207** [comment]
Hi @marekkalnik do you have any other troubleshooting ideas for me to make my time total correctly? I have combed my settings and cannot determine the problem. My 30 minute slots only count as 25 minutes, and hour+ events only work give me 50 minutes for every hour of time spent

![Screen Shot 2021-11-05 at 11 54 00 AM](https://user-images.githubusercontent.com/93665070/140548503-256f2e3a-e53f-42ed-9f15-7a862fd11416.png)
.

**Comment by marekkalnik** [comment]
We would need to replace the hardcoded height of an hour by querying the height of the mmsF1c element:
![image](https://user-images.githubusercontent.com/548629/140649040-6f37e54e-709c-4a97-8af0-71cb511bd9ae.png)

Not sure how reliable are the class names in Google Calendar. @louiszawadzki any idea?

**Comment by marekkalnik** [comment]
Or maybe it would be easier to have a setting that would set the height of one hour userside ?

**Comment by rachel49207** [comment]
Full disclosure, I am a huge fan of the extension but am a school district employee utilizing the extension. So, I have no idea what your prior response means, haha! If there is anything I can do on my end to get the extension performing properly, please let me know. I have told others in my organization and they are very excited about this addition to Google Calendar, but I have no idea how to help with the problem in the current context. Thanks @marekkalnik !

**Comment by marekkalnik** [comment]
What it means is that we don't have a technical solution to the problem yet, because it's really difficult to understand in Google Calendar's code what is the size of 1 hour. But we have some ideas so it should be fixed in few days. Hold tight :)

**Comment by rachel49207** [comment]
Awesome, I REALLY appreciate your work to fix this! Thanks so much! You have created something wonderful!

**Comment by louiszawadzki** [comment]
Hi @rachel49207.

First thank you very much for your kind comments 😃
I have submitted a fix for your problem, it is being reviewed by Google and should be updated within a few days.

I'll let you know here when you can test again :) 

Thanks a lot,
Louis

**Comment by louiszawadzki** [comment]
Hi, the fix has been released, and should have been updated for everyone automatically. I'm closing the issue, anyone can feel free to re-open it if it happens again, as Google Calendar can change its behaviour.

**Comment by rachel49207** [comment]
THANK YOU!
